version = 1

[merge]
method = "squash"
require_automerge_label = true
automerge_label = "automerge"
delete_branch_on_merge = true
auto_update = true

[merge.test]
required_status_checks = ["ci/circleci: build"]
